default_stages: [ push ]
repos:
    -   repo: local
        hooks:
            -   id: install
                pass_filenames: false
                name: Install dependencies
                entry: make install
                language: system

            -   id: reformat
                pass_filenames: false
                name: Reformat package
                entry: make reformat
                language: system

            -   id: lint
                pass_filenames: false
                name: Lint package
                entry: make lint
                language: system

            -   id: test
                pass_filenames: false
                name: Test package
                entry: make test
                language: system

            -   id: docs
                pass_filenames: false
                name: Generate documentation
                entry: make docs
                language: system

            -   id: build
                pass_filenames: false
                entry: make dist
                name: Generate build
                language: system
